
server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: brahminvaibhavgaur@gmail.com
    password: xvxp eevs uysi sori
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
